### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by tre-pengxu** [tyshiwo/MemNet#1]

**Comment by tyshiwo** [comment]
Hi, since I am busy with my staff in company, the code will be released this weekend. Sorry for the delay.

**Comment by adonishong** [comment]
looking forward to your code

**Comment by wonderDay** [comment]
looking forword to your code very much

**Comment by DouSong** [comment]
looking forward to your code very much ++, benefit from your papers and code a lot !!!

**Comment by tyshiwo** [comment]
Hey guys, I have released the code. Feel free to contact me if there is any problem! Thanks.
