### ISSUE TITLE
Performance of other optimizer?

### ISSUE THREAD

**Issue by guolu-home** [tyshiwo/MemNet#2]
Did you try to adopt other optimizers such as Adam in your experiments?  Is there a decrease in performance if other optimizer is used?

**Comment by tyshiwo** [comment]
Hi, I tried Adam and got slightly worse results than SGD, but converged much faster.

**Comment by guolu-home** [comment]
@tyshiwo  thanks. SGD is too slow. I wonder if I can use adam if there is only a little degeneration (0.02db or less).

**Comment by guolu-home** [comment]
By the way, could you provide your solver configuration when you use adam? thanks vary much!

**Comment by tyshiwo** [comment]
Hi,

I didn't backup this file, sorry for that.
